[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[envs]]
NODE_ENV = "production"
PORT = "3000"
JWT_EXPIRES_IN = "1h"
ALLOWED_ORIGINS = "*"
DATABASE_URL = "${{sm-portal-db.DATABASE_URL}}"
REDIS_URL = "${{sm-portal-redis.REDIS_URL}}"
JWT_SECRET = "gmp_super_secret_jwt_key_2024_abcdef123456"
ADMIN_EMAIL = "admin@grantportal.com"
ADMIN_PASSWORD = "Admin@123456"
