services:
  - type: web
    name: sm-portal-app
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: sm-portal-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          type: redis
          name: sm-portal-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: sm-portal-redis
          property: port
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: SEED_ON_START
        value: "true"
      - key: ADMIN_EMAIL
        value: admin@grantportal.com
      - key: ADMIN_PASSWORD
        value: Admin@123456
      - key: OAUTH_CLIENT_ID
        value: placeholder_github_client_id
      - key: OAUTH_CLIENT_SECRET
        value: placeholder_github_client_secret
      - key: OAUTH_CALLBACK_URL
        value: https://sm-portal-app.onrender.com/api/auth/github/callback
      - key: ALLOWED_ORIGINS
        value: "*"

  - type: redis
    name: sm-portal-redis
    plan: free
    ipAllowList: []

databases:
  - name: sm-portal-db
    databaseName: gmpdb
    user: gmpuser
    plan: free
